### ISSUE TITLE
License switch to OSL3?

### ISSUE THREAD

**Issue by fballiano** [firegento/firegento-dynamiccategory#76]
Hi everybody, the module is released under GPL3 but this makes it hard to integrate it into OSL based project, since OLS (magento1/openmage license) is not compatible with GPL.

I'd love to promote this module in the openmage community, but at the moment this is not possible to me.

would you consider switching to OSL3?

**Comment by riconeitzel** [comment]
Sounds legit to me. With „integrate“ you mean install as external component or take fragments into OpenMage?

**Comment by sreichel** [comment]
OM does not include this module. I don't see any license violation.

I think it's no problem to promote an extension with another license.

Maybe I misunderstand "promote", but o/c you can promote/advertise modules that use other licenses.

**Comment by fballiano** [comment]
@sreichel as I already explained OSL is not compatible with GPL, so, I personally (I never spoke about OM) won't promote a module having a license that's not compatible withe the one in OM. also, if you install a GPL module all of your project would become GPL (although it's a bit debatable) so I'd never install a GPL module in a OSL project.

and I love GPL software, I've been ad advocate for AGPL since 2009 on my blog, the validity of the license is not the point of this request.

**Comment by fballiano** [comment]
@riconeitzel it would be nice to have this functionality in the core but in OM I've always seen a preference to have external modules instead of bringing functionalities inside, this is for many correct reasons, and it's totally fine.
but also from a commercial perspective I can't suggest people to install a GPL module unless they specifically know what they're doing, but the incompatibility between the licenses still stands as a problem: https://gplv3.fsf.org/wiki/index.php/Compatible_licenses

**Comment by sreichel** [comment]
@fballiano i thinks you're one a wrong track.

OM code is released under OSL/AFL license.

Zf1-future has it own proprietary license, same as all Amasty extensions. (E.g.)

Of course you can use/promote it.

It may be different when you want to make this code part of OM.

But ... please do not start to add extensions/features to core!!!

In all that years we added only one extension to core ... N98_LayoutHelper that provided same very very basic features.

**Comment by sreichel** [comment]
> @riconeitzel it would be nice to have this functionality in the core but in OM I've always seen a preference to have external modules instead of bringing functionalities inside, this is for many correct reasons, and it's totally fine.
> 
> but also from a commercial perspective I can't suggest people to install a GPL module unless they specifically know what they're doing, but the incompatibility between the licenses still stands as a problem: https://gplv3.fsf.org/wiki/index.php/Compatible_licenses

No. It should not be integrated into core!!!

That's what are extensions for ... to add new features.

Please not!

**Comment by therouv** [comment]
Hi everyone, original module author here :) 

Our main goal was to ensure that if someone modifies the code, they either release it as Open Source themselves or contribute those changes back to this project.

We chose the GPL license because it allows you to use the module in your projects, including closed-source projects, and even make modifications without needing to release the entire codebase as Open Source. For more details, see [GNU's FAQ](https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic).

In practice, customers using an OSL-based project (like OpenMage) can use this plugin without issues, as the customer application would never be released publicly.

The only scenario where a license change for this extension would make sense is if someone wanted to fork the project, modify the code, and integrate it as a native extension into another project. This was never our intention and, from my perspective, it's still not something we want.

But even if we wanted to change the license, we could never switch to OSL3 because we could only change it to another Free Software Foundation (FSF)-approved license that is compatible with GPLv3. It would also require consent from all contributors of this extension.

**Comment by fballiano** [comment]
I understand the intent behind choosing GPL, as I said I was advocating for magento itself being AGPL in 2009-2010, problem is that now if you use a GPL module in a project you're at risk of having to make the whole project GPL, that's why the licenses are marked as incompatible.
Magento chose to be OSL because they didn't want to force businesses to open source their projects. This is also why embedded vendors have dedicated websites for their GPL based software, because they're forced to do it.
Having an incompatible license makes it impossible to use this module, at least this is what I know, it's a complicated matter but it wouldn't be if the licenses were compatible.
It's a pity, because this module seems very nice but unfortunately I wouldn't use it for my customers nor I would extend it.
